### ISSUE TITLE
[PROPOSAL] Changelog should mention what changed in version 2.0.1

### ISSUE THREAD

**Issue by deepai-org** [opensearch-project/opensearch-py#247]
The changelog does not even mention version 2.0.1

**Comment by wbeckler** [comment]
This is totally valid. I think this is because the automated changelog was added since the previous release. Here's the release notes: https://github.com/opensearch-project/opensearch-py/releases/tag/v2.0.1

There's also the need to do a minor version increment: https://github.com/opensearch-project/opensearch-py/issues/248

**Comment by harshavamsi** [comment]
Hi @deepai-org I'm updating the changelog in #249 to reference the released version. In the meanwhile, you can check the release notes [here](https://github.com/opensearch-project/opensearch-py/releases/tag/v2.0.1)
