### ISSUE TITLE
[FEATURE] Ability to execute a single unit/integration test

### ISSUE THREAD

**Issue by harshavamsi** [opensearch-project/opensearch-py#317]
### Is your feature request related to a problem?
So I'd like to execute a single unit/integration test locally. This makes it easier to test just that single feature that I am working on rather than executing the entire suite of tests.

### What solution would you like?
A way for me to do `./.ci/run-tests true 1.3.0 test_async/test_keep_alive_is_on_by_default`

**Comment by elamirKad** [comment]
I will work on this issue

**Comment by elamirKad** [comment]
My overall plan:
I want to pass which test to execute to run_tests.py file, so I need to
1) Find a way how to pass this variable from 'run-tests' script to 'test_opensearchpy/run_tests.py' (current idea: add the variable name when running docker)
2) Run specific test inside 'run_test.py' (current idea: add new function run_specific and execute command by adding -v flag when running pytest)

My plan on how I will pass the name of the test to the run_tests.py:
1) I would add `export TEST_NAME="${3:-}"` to 'run-tests' script
2) Inside 'run-test', I would change `bash .ci/run-repository.sh` to `bash .ci/run-repository.sh`
3) I would add `TEST_NAME="${1:-}"` to 'run-repository.sh'
4) In 'run-repository.sh' I would add this line `--env "TEST_NAME=${TEST_NAME}" \` in docker run command
5) Optional: I would add `if [[ -z "$TEST_NAME" ]]; then` to check if TEST_NAME variable was provided. If not, I would run the current docker run command
6) I probably would unset this env variable by `unset TEST_NAME` at the end so that It wouldn't be used in the next runs

My plan on what I would do in 'run_tests.py':
1) I would add a new function, `run_specific(argv)`
2) In `if __name__ == "__main__":` I would check if environment variable 'TEST_NAME' exists (`TEST_NAME = os.environ.get("TEST_NAME", "")`) and would run function depending on if env variable 'TEST_NAME' exists.
3) Inside run_specific(argv) I would edit argv by something like `["pytest", "-v", TEST_NAME]`, I would also modify 'TEST_NAME' in this way (`test_async/test_connection.py/test_keep_alive_is_on_by_default` -> `test_async/test_connection.py::test_keep_alive_is_on_by_default`)
4) Optional: I can create some function to retrieve specific tests from the whole folder if it is required
5) Then I would run a subprocess like in run_all():
`
try:
        subprocess.check_call(argv, stdout=sys.stdout, stderr=sys.stderr)
except subprocess.CalledProcessError as e:
        exit_code = e.returncode
`

I would greatly appreciate any feedback you have to offer!

**Comment by elamirKad** [comment]
I decided to proceed with the "-k" flag for pytest.

**Comment by harshavamsi** [comment]
> 

Hi, firstly this is fantastic. Thank you very much! I think your approach is really good and fits the use-case.

I'm curious, does this also work for the unit tests? If not, would you need to make changes in the bash files or in `run_tests.py`? I see that run_tests.py pulls in opensearch, we might want to clean that up if it's only being used by the unit tests.

**Comment by harshavamsi** [comment]
> My overall plan: I want to pass which test to execute to run_tests.py file, so I need to
> 
>     1. Find a way how to pass this variable from 'run-tests' script to 'test_opensearchpy/run_tests.py' (current idea: add the variable name when running docker)
> 
>     2. Run specific test inside 'run_test.py' (current idea: add new function run_specific and execute command by adding -v flag when running pytest)
> 
> 
> My plan on how I will pass the name of the test to the run_tests.py:
> 
>     1. I would add `export TEST_NAME="${3:-}"` to 'run-tests' script
> 
>     2. Inside 'run-test', I would change `bash .ci/run-repository.sh` to `bash .ci/run-repository.sh "${TEST_NAME}"`
> 
>     3. I would add `TEST_NAME="${1:-}"` to 'run-repository.sh'
> 
>     4. In 'run-repository.sh' I would add this line `--env "TEST_NAME=${TEST_NAME}" \` in docker run command
> 
>     5. Optional: I would add `if [[ -z "$TEST_NAME" ]]; then` to check if TEST_NAME variable was provided. If not, I would run the current docker run command
> 
>     6. I probably would unset this env variable by `unset TEST_NAME` at the end so that It wouldn't be used in the next runs
> 
> 
> My plan on what I would do in 'run_tests.py':
> 
>     1. I would add a new function, `run_specific(argv)`
> 
>     2. In `if __name__ == "__main__":` I would check if environment variable 'TEST_NAME' exists (`TEST_NAME = os.environ.get("TEST_NAME", "")`) and would run function depending on if env variable 'TEST_NAME' exists.
> 
>     3. Inside run_specific(argv) I would edit argv by something like `["pytest", "-v", TEST_NAME]`, I would also modify 'TEST_NAME' in this way (`test_async/test_connection.py/test_keep_alive_is_on_by_default` -> `test_async/test_connection.py::test_keep_alive_is_on_by_default`)
> 
>     4. Optional: I can create some function to retrieve specific tests from the whole folder to remove `/test_connection.py` from `test_async/test_connection.py/test_keep_alive_is_on_by_default`
> 
>     5. Then I would run a subprocess like in run_all():
>        `try: subprocess.check_call(argv, stdout=sys.stdout, stderr=sys.stderr) except subprocess.CalledProcessError as e: exit_code = e.returncode`
> 
> 
> I would greatly appreciate any feedback you have to offer!

Hi, firstly this is fantastic. Thank you very much! I think your approach is really good and fits the use-case.

I'm curious, does this also work for the unit tests? If not, would you need to make changes in the bash files or in `run_tests.py`? I see that run_tests.py pulls in opensearch, we might want to clean that up if it's only being used by the unit tests.

**Comment by elamirKad** [comment]
I'm glad that my idea is appropriate for this use case :D! I believe this approach should also work for unit tests. However, I will conduct more tests to ensure its effectiveness.

I encountered some issues with checks during PR, but I will troubleshoot them as soon as possible. It's likely that these problems can be resolved by tweaking the logic of environment variables.
