### ISSUE TITLE
[CCI][BUG]  Httpbin.org intermittently stops responding, which fails some tests

### ISSUE THREAD

**Issue by bl1nkker** [opensearch-project/opensearch-py#327]
### What is the bug?
[httpbin.org](http://httpbin.org/) gives 504 error intermittently, and since [some tests](https://github.com/opensearch-project/opensearch-py/blob/409c883013c3cbae45cf12ecf501af2851ec53f7/test_opensearchpy/test_connection.py#LL871) in the opensearch-py check the connection to [httpbin.org](http://httpbin.org/), the whole ci fails because the tests cannot send a request to this third party service.

### How can one reproduce the bug?
Try to run the test several times

### What is the expected behavior?
Tests will throw:
`
test_opensearchpy/test_connection.py::TestConnectionHttpbin::test_urllib3_connection - opensearchpy.exceptions.TransportError: TransportError(504, '<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n</body>\r\n</html>\r\n')
FAILED test_opensearchpy/test_async/test_connection.py::TestConnectionHttpbin::test_aiohttp_connection - opensearchpy.exceptions.ConnectionTimeout: ConnectionTimeout caused by - TimeoutError()
`

### What is your host/environment?
macOS Monterey 12.2.1 (M1 chip)
Python v3.11

### Do you have any screenshots?
<img width="658" alt="image" src="https://user-images.githubusercontent.com/57720347/225687526-9a58821c-e078-4a71-b29a-91036c9b9980.png">

### Do you have any additional context?
[httpbin.org 1](http://httpbin.org/) may be experiencing high load, which could be causing the server to respond slowly or not at all

**Comment by bl1nkker** [comment]
We have already discussed this problem with another student and we have some ideas how to fix this problem.

But first, we would like to hear the opinion of the mentors and developers of this repository

**Comment by Refffy** [comment]
I'll duplicate my answer about our discussion with @bl1nkker from CCI forum:
The problem in my opinion is that httpbin can’t process requests because of heavy load, I realized this because the resource itself is working properly when accessing it, even when timeout errors occur in the test.
I think we should try to set a timeout on the http client which sends requests and handle the TimeoutError exception, if we intercepted it, then setting a flag or interrupting the function execution (e.g. if handled: return).
Pros: easy to implement, understand and maintain, and it seems like a solution of the problem.
Cons: as you mentioned in our discussion in contributors chat, we can face a situation, when httpbin won’t respond at all because it may fall, not only in test but in general. But I think, we don’t need to care about that, because requests from client side because requests are made as needed so there’s no need to try resending them in background or doing a healthcheck.
Summarize:
    1) set timeout for http client
    2) handle the TimeoutError exception
    3) do an error propagation or setting a flag/value, which will be an indicator of httpbin availability
#Example (pseudocode):
```python
def some_test():
  try:
    conn = Urllib3HttpConnection("httpbin.org", ..., timeout=60)
    ...some other stuff...
  except (TimeoutError, ConnectionError):
    raise TimeoutErrorException() # or return some flag
 ```
 And another approach is to mock the requests to httpbin in tests, it'll extreamly reduce the latency of the requests and responses to httpbin.

**Comment by bl1nkker** [comment]
@VachaShah  I recently reviewed the project. Does it really need httpbin? It feels like it's just a normal stub to test the connection as a whole
<img width="291" alt="image" src="https://user-images.githubusercontent.com/57720347/226434948-a4819906-f0ae-4727-8820-d46afcc15d0f.png">

**Comment by wbeckler** [comment]
The number one reason not to use a service like httpbin.org is that it could go down and cause flaky tests. Well since that has happened, it makes total sense to find an alternative way to test this code path.

**Comment by VachaShah** [comment]
I agree that we could find an alternative to httpbin.org so we can avoid tests failing because of the dependency.

**Comment by dblock** [comment]
Start a rudimentary web server inline with tests or mock the HTTP requests?

**Comment by Refffy** [comment]
@dblock  yes, I suggested to mock the requests in my answer above, I think it's a good approach

**Comment by harshavamsi** [comment]
The HTTPBin tests are for testing the various connection options(RequestsHttpConnection, UrlLib3Connection) against a *live* server. There are no other live tests in the client. The only other tests that reference these are mock connections. For the purposes of test coverage and good practices, I believe we should either switch to another service or expand these tests by running them against a local running server. Mocking isn't an option here because that does not achieve testing the service against a live endpoint. Happy to assist!

**Comment by dblock** [comment]
If we need live tests, +1 on a locally spawned server in the test.

**Comment by ReinGrad** [comment]
error 504 when running tests that check the connection to httpbin.org . Since some tests in opensearch-py rely on httpbin.org , the whole CI fails because the tests cannot send a request to this third-party service. The error can be reproduced by running the test multiple times, and the expected behavior is that the tests will give an error due to a connection timeout or a transport error.

### Possible Solutions 1

The proposed solution to this error is to set a timeout on the http client that sends requests and handles the TimeoutError exception. If an exception is caught, set the flag or abort the function. The advantage of this solution is that it is easy to implement, understand and maintain. However, there is a risk that httpbin.org it does not react at all due to the heavy load, not only in tests, but in general. In this case, there would be no need to resend requests in the background or perform a health check.

### Possible Solutions 2

Other suggested solutions for this error include simulating requests to httpbin.org in tests or searching for an alternative httpbin.org to avoid test failures due to dependency. The tests are designed to test various connection options (RequestsHttpConnection, UrlLib3Connection) to an active server. There are no other live tests in the client, and in order to ensure test coverage and good practice, it would be better to either switch to another service or extend these tests by running them on a locally running server.

**Comment by wbeckler** [comment]
Why not run httpbin locally? Including it as a dependency shouldn't be a license problem because its [license](https://github.com/postmanlabs/httpbin/blob/master/LICENSE) is OSI-approved. It does look untouched for the last 5 years. But maybe that's better than a website that flakes.

**Comment by dblock** [comment]
All these are good proposals! Appreciate a PR from someone. Thanks in advance.
