### ISSUE TITLE
[BUG] AWSV4SignerAuth doesn't freeze credentials before signing, leading to a race condition

### ISSUE THREAD

**Issue by lattwood** [opensearch-project/opensearch-py#423]
### What is the bug?
AWSV4SignerAuth passes the raw credentials object to SigV4Auth, instead of checking for a `get_frozen_credentials` method and calling that. This leads to the access key for a request differing from the secret key used to sign it.

### How can one reproduce the bug?

1. Setup your AWS SDK with a refreshable credential mechanism.
2. Sign requests like it's going out of business
3. When you cross the refresh threshold, you'll get a request indicating it was signed with a different key than it actually was.

### What is the expected behavior?
All requests get signed with matching access keys & secrets.

### Do you have any additional context?
See this Python docstring in botocore for a more thorough explanation of the problem.

https://github.com/boto/botocore/blob/c29640a5e7a5f77cc4c6bb27e30a5387bc12832a/botocore/credentials.py#L399-L406

**Comment by ReinGrad** [comment]
The problem here is that AWSV4SignerAuth passes raw credentials to SigV4Auth instead of frozen/static credentials. This leads to a potential race condition when signing requests across the credential update boundary.

The behavior is that all requests must be signed with a consistent set of credentials - the same access key identifier and a pair of secret keys. However, with the credentials being updated, if requests are made via an update, the access key identifier in the header may not match the secret key used in the signature.

As explained in the botocore docs here:

https://botocore.readthedocs.io/en/latest/reference/credentials.html#token-race-condition

To avoid this race condition, you should use frozen credentials instead of raw credential objects. The frozen credentials are a snapshot of the credentials at the time of signing the request.

The fix would be to update AWSV4SignerAuth to check for the `get_frozen_credentials()` method in the credentials object, call it first, and then pass the frozen credentials to SigV4Auth to generate the signature. This ensures that the header and signature use a consistent set of access key identifier and secret key.

**Comment by lattwood** [comment]
That’s… what I said?

**Comment by saimedhi** [comment]
Hello @ReinGrad, please feel free to take up this issue and raise a PR with your proposed solution. Thanks :)

**Comment by lattwood** [comment]
@saimedhi PR opened https://github.com/opensearch-project/opensearch-py/pull/469
