### ISSUE TITLE
[FEATURE] Add support for server-side APIs that are currently not implemented in the client

### ISSUE THREAD

**Issue by saimedhi** [opensearch-project/opensearch-py#435]
### What solution would you like?
Add support for server-side APIs that are currently not implemented in the client

**Comment by dblock** [comment]
Since we added code generation from spec I am going to close this. We have issues for specific APIs missing under the [plugin support](https://github.com/opensearch-project/opensearch-py/issues?q=is%3Aopen+is%3Aissue+label%3A%22plugin+support%22) label for example for plugins, so anyone reading this please open a new issue for any specific API missing.
