### ISSUE TITLE
[NEW RELEASE] Request to prepare & release 2.5.1

### ISSUE THREAD

**Issue by james-certn** [opensearch-project/opensearch-py#733]
Currently, version 2.5.0 is incompatible for a subset of users, and is easily fixed by the work done in #719. 

As such, I propose a release to go out as soon as reasonably possible, to unblock those folks.

**Comment by jayaddison** [comment]
Hi @james-certn - this is slightly confusing; we have the same full name.  I think I spoke to you once on an Elasticsearch IRC channel.  Anyway, hello.

Could someone confirm whether this release process _requires_ use of the [release drafter GitHub Actions workflow](https://github.com/opensearch-project/opensearch-py/blob/303b6c6f6467b1cd378b055d722ffcee95440329/.github/workflows/release-drafter.yml)?

The reason I ask: I have a concern that the release drafter workflow may have unnecessary permissions; in particular I don't think that it should need the [`contents: write` permission](https://github.com/opensearch-project/opensearch-py/blob/303b6c6f6467b1cd378b055d722ffcee95440329/.github/workflows/release-drafter.yml#L12).

That in itself is not a problem - something else would need to go wrong for it to write incorrect/unrelated content into the repo.  But if someone could check, that could be worthwhile.  I'll prepare a PR to drop that permission, although if the permission _is_ indeed intended and required for some reason, then I will subsequently close it.

**Comment by jayaddison** [comment]
Ok, my apologies - reading the [GitHub Actions `contents` workflow permissions documentation](https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-contents), it does seem that this permission is required to create a release artifact -- and that I suppose is something that the [`upload windows dists` step](https://github.com/opensearch-project/opensearch-py/blob/303b6c6f6467b1cd378b055d722ffcee95440329/.github/workflows/release-drafter.yml#L38-L42) is intended to do.

It does seem that the same token permission also provides the ability to [create a commit](https://docs.github.com/en/rest/git/commits?apiVersion=2022-11-28#create-a-commit) within the repository -- something that I _don't_ think we'd expect or want the job to do (it's fine to read the repository sources, and to create a redistributable object -- but it shouldn't need to write to version control).

However, I don't initially find documented configuration settings that would allow a release artifact to be published _without_ granting the write permission that also allows writes to version control.  I may be mistaken, and will continue to investigate, but I don't think that this should be considered a blocker.  My apologies for the distraction if this turns out to be nothing.

**Comment by james-certn** [comment]
>Hi @james-certn - this is slightly confusing; we have the same full name. I think I spoke to you once on an Elasticsearch IRC channel. Anyway, hello.

Well, hello again then. ;)  James Addisons of the world, unit!

**Comment by saimedhi** [comment]
Hello @jayaddison,

The release process for the project utilizes the [Release Drafter GitHub Actions workflow](https://github.com/opensearch-project/opensearch-py/blob/main/.github/workflows/release-drafter.yml). And write permissions are required for this process.

**Comment by jayaddison** [comment]
Thank you @saimedhi for confirming that :+1: 

Please consider my question resolved.

**Comment by saimedhi** [comment]
Hello @james-certn,

I plan to release opensearch-py version 2.6.0 after a few pending pull requests are merged. You can check the status of these PRs [here](https://github.com/opensearch-project/opensearch-py/pulls?q=is%3Aopen+is%3Apr+label%3A%22opensearch-py+2.6.0%22).

Thank you for your patience!

**Comment by saimedhi** [comment]
+1  https://github.com/opensearch-project/opensearch-py/issues/628#issuecomment-2125757146

**Comment by skshetry** [comment]
@saimedhi, was this released? I don't see it tagged or in PyPI.

**Comment by dblock** [comment]
Looks like version was bumped but no release (yet).

**Comment by saimedhi** [comment]
I'm planning to release version 2.6.0 today. Thank you!

**Comment by saimedhi** [comment]
opensearch-py [version 2.6.0](https://pypi.org/project/opensearch-py/2.6.0/) is now released!
