### ISSUE TITLE
Update README with installation

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-py#79]
Update README with feedback from here: https://github.com/opensearch-project/opensearch-py/pull/76

**Comment by wbeckler** [comment]
Since this was first opened, this information has been added to [GETTING_STARTED.md](https://github.com/opensearch-project/opensearch-py/blob/main/). There are mentions of both `pip install` and `git` but a little more tersely than originally proposed. Unless there are any objections, I would propose we close this as solved.
