### ISSUE TITLE
[BUG] Unable to index documents in Amazon OpenSearch Serverless collection index with a custom ID

### ISSUE THREAD

**Issue by goelsunny87** [opensearch-project/opensearch-py#792]
### What is the bug?
We're unable to index the documents in `Amazon OpenSearch Serverless` collection with a custom ID using opensearch-py client. We do see the following error in Cloud Watch logs. 

```
RequestError(400, 'illegal_argument_exception', 'Document ID is not supported in create/index operation request')
```

### How can one reproduce the bug?
Create a simple python based application to index documents into Amazon OpenSearch Serverless collection. Please ensure that you leverage `opensearch-py==2.6.0` in the `requirements.txt` file

### What is the expected behavior?
Expected behavior is to be able to index documents in Amazon OpenSearch Serverless collection with a custom ID using opensearch-py client.

**Comment by dblock** [comment]
Post a repro please? But either way I would first narrow this down to a python client problem and not a serverless limitation or something else.

1. Can you reproduce this with `curl`?
2. Does this happen against a local installation of OpenSearch.
3. Does this happen against Amazon Managed OpenSearch vs. Serverless.

**Comment by goelsunny87** [comment]
@dblock - I haven't tried this with local installation of OpenSearch. It's presently happening with Amazon managed OpenSearch Serverless collection.

**Comment by dblock** [comment]
@goelsunny87 Understood, please see above for what to do next.

**Comment by dblock** [comment]
Most likely this is expected behavior depending on the collection type https://docs.aws.amazon.com/opensearch-service/latest/developerguide/serverless-overview.html#serverless-usecase - _For time series and vector search collections, you can't index by custom document ID or update by upsert requests. This operation is reserved for search use cases. You can update by document ID instead._

Going to close this for now as this isn't a bug in the python client.
